### ISSUE TITLE
Add support for definitions keyword

### ISSUE THREAD

**Issue by ericoporto** [tangram-js/json-schema-editor#10]
It's not possible to create schema definitions to be reused. Instead each has to be a separated file using the ref repository

**Comment by tangram-js** [comment]
Yes, JSON Schema Editor is not fully compliant with JSON schema, it could only handle the "schema elements" listed in the "Pallet of schema elements", which not include the "definitions".
The structure of "definitions" could be very flexible, there is no way to extract finite "schema elements" from all possible content of "definitions", unless we restrict the "definitions" with fixed pattern.
This issue has been solved in the successor of JSON Schema Editor, JSON Editor, which is a schema-aware editor for JSON document including JSON schema. It can use official meta schema of JSON schema to edit JSON schema documents, including the "definitions".

**Comment by tangram-js** [comment]
Well, by most use cases, the structure of "definitions" should be very similar with "properties". With such restriction, I could add a new schema element "definitions" to the "Pallet of schema elements".

**Comment by ericoporto** [comment]
That could work. We need too to be able to use ref:#/definitions/ADEFINITION . Basically, `#` should be understood as repository:SELF .

Something similar to:

    {
      "definitions": {
        "address": {
          "type": "object",
          "properties": {
            "street_address": { "type": "string" },
            "city":           { "type": "string" },
            "state":          { "type": "string" }
          },
          "required": ["street_address", "city",  "state"]
        }
      },
      "type": "object",
      "properties": {
        "billing_address": { "ref": "#/definitions/address" },
        "shipping_address": { "ref": "#/definitions/address" }
      }
     }

**Comment by tangram-js** [comment]
It's done!
