### ISSUE TITLE
enum property being wrong created

### ISSUE THREAD

**Issue by mhddenno** [tangram-js/json-schema-editor#14]
When I add to a string or integer type an enum, the enum should be an array like this:
`            "type": "string",
            "enum": {
                "enum": [
                    "true"
                ]
            }`
But it is wrong because it should be generated as an array without being wrapped with an "enum" object.
The right way should be something like this:
`
            "type": "string",
                "enum": [
                    "true"
                ]
`

**Comment by tangram-js** [comment]
It's fixed.
