### ISSUE TITLE
Enum property should not take the belonged object properties

### ISSUE THREAD

**Issue by mhddenno** [tangram-js/json-schema-editor#15]
If I want to add the following object in my schema:
             `"prop(1)": {
                    "type": "number",
                    "minimum": 5,
                    "maximum": 10,
                    "enum": [100]
                }`
The following error will appear 

> should be <= 10

although that's not supposed to be!

**Comment by tangram-js** [comment]
The error comes from the schema validator.
Using your schema and validate 100 as JSON would get the same error from following online JSON validators:

- [JSON Schema validation online]( https://json-schema-validator.herokuapp.com)
- [JSON Schema Lint :: JSON Schema Validator](https://jsonschemalint.com/#/version/draft-07/markup/json)

**Comment by mhddenno** [comment]
You are right my bad!
