### ISSUE TITLE
Integer/Number min/max incorrect.

### ISSUE THREAD

**Issue by jetedrow** [tangram-js/json-schema-editor#18]
According to the reference guide (https://json-schema.org/understanding-json-schema/reference/numeric.html#range) the valid values for defining ranges are:

- minimum
- maximum
- exclusiveMinimum
- exclusiveMaximum

The current version of the schema editor currently sets the **excludeMinimum** and **excludeMaximum** properties to a boolean value.  I believe this to be incorrect as I can not find any references in the json schema RFC to these values.  I believe this to be an issue that needs to be corrected.

Please let me know if any additional information is required.

**Comment by tangram-js** [comment]
In JSON Schema Draft 4, exclusiveMinimum and exclusiveMaximum work differently. There they are boolean values, that indicate whether minimum and maximum are exclusive of the value.
Currently, they should be numerical value. I will update that.

**Comment by tangram-js** [comment]
It's done.
