### ISSUE TITLE
Please input number

### ISSUE THREAD

**Issue by PhilippeMalric** [tangram-js/json-schema-editor#2]
When I try to write the maximum value of a number it give me always the same error : Please input number.

**Comment by idjhuang** [comment]
Thanks for point out the error! The validate method for number has problem, and it has been fixed in the source code.
The live demo has not updated yet, because it's on the progress to merge a new JOSN editor, and it well be done together.

**Comment by tangram-js** [comment]
Thanks for point out the error! There is a bug in the validate method of BasicInspector.vue and it has been fixed in the source code.
The live demo has not been updated yet, for there is a merge of JSON editor demo on progress, it would be done together.
