### ISSUE TITLE
$ref can't be saved in firebase as a key because it contains '$'

### ISSUE THREAD

**Issue by othermark** [tangram-js/json-schema-editor#5]
Save custom schema error: Firebase.set failed: First argument contains an invalid key ($ref) in property 'schemas.xOW3vBZG7JSxJcqfilsEdUJ0ZnI2.Pool.items.0'. Keys must be non-empty strings and can't contain ".", "#", "$", "/", "[", or "]"

{
    "type": "array",
    "items": [
        {
            "$ref": "repository://Pool_member"
        }
    ],
    "title": "Pool",
    "description": "Pool"
}

**Comment by tangram-js** [comment]
Thank you for point out the bug, it's fixed now.

**Comment by othermark** [comment]
This only seems to work for top level items since your fix doesn't recurse into the anonymous array where $refs are held because of the !Array.isArrayType(value)

example:
```
{
    "type": "object",
    "properties": {
        "member": {
            "oneOf": [
                {
                    "$ref": "repository://IPv4 Address"
                },
                {
                    "$ref": "repository://IPv6 Address"
                }
            ]
        },
        "Port": {
            "$ref": "repository://Port"
        }
    },
    "title": "PoolMember",
    "description": "Pool Member"
}
```

**Comment by tangram-js** [comment]
Wow! You are right! It's fixed and thank you again!
