### ISSUE TITLE
Possibility of exposing this project as a component library?

### ISSUE THREAD

**Issue by lexwebb** [tangram-js/json-schema-editor#6]
Hi there,

I've been looking for a way to embed a json schema editor into a project of mine (Happens to be made in Vue 2 aswell), and i came accross your repository here.

Is there any chance that this project could be made into a view componet/component lribary? That would make it much easier for this to be embeded into existing applications.

If not, would it be alright for me to fork this, and turn it into a component library?

**Comment by tangram-js** [comment]
This project is heavily coupled with vue-material and firebase, it would take some effort to isolate these features to become a standalone component. I think you would like to remove these dependencies right?
On the other hand, the json-editor project is successor of this project, which could edit generic JSON document, including JSON schema. That project is quite self-contained, and is more easy to package as a view component/component library, would you take a look on that?

**Comment by lexwebb** [comment]
Thanks, as you said it looks like much easier to adapt. I'll take a look into what would need to be done. Many thanks for the quick response!
