### ISSUE TITLE
"type" as a property key is not supported

### ISSUE THREAD

**Issue by msiladin** [tangram-js/json-schema-editor#7]
When importing a schema that has a property with a key named "type" the editor reports an error:
Load schema from file error: JSON.parse: expected ',' or '}' after property value in object at line 83 column 7 of the JSON data

The property looks like this:
    "Membership": {
      "type": "object",
      "properties": {
        "level": {
          "description": "Status or level of membership.",
          "type": "string"
        },
        "name": {
          "description": "The name of the membership.",
          "type": "string"
        },
        "number": {
          "description": "The membership number assigned to the member.",
          "type": "string"
        },
        **"type": {**
          "description": "The type of membership.",
          "type": "string"
        }
      }

**Comment by idjhuang** [comment]
The error message "JSON.parse: expected ',' or '}' after property value in object at line 83 column 7 of the JSON data" indicates you missing a "}" in your schema.
I can import following schema which use "type" as a property key with no problem: 
```
{
	"title": "test issue 7",
	"type": "object",
	"properties": {
		"level": {
			"description": "Status or level of membership.",
			"type": "string"
		},
		"name": {
			"description": "The name of the membership.",
			"type": "string"
		},
		"number": {
			"description": "The membership number assigned to the member.",
			"type": "string"
		},
		"type": {
			"description": "The type of membership.",
			"type": "string"
		}
	}
}
```

**Comment by tangram-js** [comment]
The error message "JSON.parse: expected ',' or '}' after property value in object at line 83 column 7 of the JSON data" indicates you missing a "}" in your schema.
I can import following schema which use "type" as a property key with no problem:
```
{
	"title": "test issue 7",
	"type": "object",
	"properties": {
		"level": {
			"description": "Status or level of membership.",
			"type": "string"
		},
		"name": {
			"description": "The name of the membership.",
			"type": "string"
		},
		"number": {
			"description": "The membership number assigned to the member.",
			"type": "string"
		},
		"type": {
			"description": "The type of membership.",
			"type": "string"
		}
	}
}
```
