### ISSUE TITLE
load from file fails with error

### ISSUE THREAD

**Issue by emlaabs** [tangram-js/json-schema-editor#9]
The "load from file" feature for the schema editor is failing with the following error:

Load schema from file error: Cannot set property 'name' of undefined

The file was created using the editor and downloaded prior to attempting to load.

**Comment by tangram-js** [comment]
Could you provide the content of the file? I can not reproduce the error.

**Comment by tangram-js** [comment]
If the field name in JSON schema is not valid, then there would be such error for "LOAD FROM FILE".
